### ISSUE TITLE
加载84坐标瓦片出现黑线

### ISSUE THREAD

**Issue by dufeng-code** [yangyanggu/amap-xyz-layer#1]
![微信图片_20240514122037](https://github.com/yangyanggu/amap-xyz-layer/assets/65160428/46a5034e-92c2-4947-a64f-fec3767d5894)

**Comment by yangyanggu** [comment]
你这是不是使用的JSAPI2.0Beta 版本

**Comment by dufeng-code** [comment]
https://www.npmjs.com/package/@vuemap/amap-xyz-layer 这是我使用的版本 "@vuemap/amap-xyz-layer": "^0.0.10"。

**Comment by yangyanggu** [comment]
> https://www.npmjs.com/package/@vuemap/amap-xyz-layer 这是我使用的版本 "@vuemap/amap-xyz-layer": "^0.0.10"。
这个要看你使用的配套的JSAPI的版本，如果是2.0Beta版本就是会这样，2.0Beta由于加了高程处理，相机对外暴露的参数出错了，导致会压缩成线，需要高德那边修改

**Comment by dufeng-code** [comment]
对，高德是用的version: "2.0"的，有什么解决方法吗

**Comment by yangyanggu** [comment]
> 对，高德是用的version: "2.0"的，有什么解决方法吗

你用的是2.0 不是Beta版本？如果只是2.0不应该有这种压缩的问题

**Comment by dufeng-code** [comment]
我是用 的AMapLoader加载的 `import` AMapLoader from '@amap/amap-jsapi-loader';
AMapLoader.load({
 version: "2.0",    }) ` ，理论上是用的2.0。但是确实有这个问题

**Comment by yangyanggu** [comment]
你使用的瓦片地址还有代码示例贴一下吧，我看下原因

**Comment by dufeng-code** [comment]
`<template>
    <div class="app-container" id="mapId">
        121
    </div>
</template>
<script setup>
import AMapLoader from '@amap/amap-jsapi-loader';
import { CustomXyzLayer } from '@vuemap/amap-xyz-layer'
AMapLoader.load({
    key: "",  // 申请好的Web端开发者Key，首次调用 load 时必填
    version: "2.0",      // 指定要加载的 JSAPI 的版本，缺省时默认为 1.4.15
    plugins: [
        'AMap.MarkerCluster', 'AMap.Polyline', 'AMap.MoveAnimation', 'AMap.CircleEditor',
        'AMap.Driving', 'AMap.AutoComplete', 'AMap.Scale', 'AMap.MouseTool', 'AMap.Geolocation', 'AMap.CitySearch', 'AMap.TileLayer'
    ],       // 需要使用的的插件列表，如比例尺'AMap.Scale'等
    Loca: {                // 是否加载 Loca， 缺省不加载
        "version": '2.0.0'  // Loca 版本，缺省 1.3.2
    },
}).then((AMap) => {
    let map = new AMap.Map('mapId', {  //设置地图容器id
        zoom: 11,
        center: [115.056789, 22.881174],
        layers: [
            // new AMap.TileLayer(),
        ],
    });

    // new AMap.GLCustomLayer
    const tiandituLayer = new CustomXyzLayer(map, {
        url: '202311%E5%8D%AB%E6%98%9F%E5%BD%B1%E5%83%8F/MapServer/tile/{z}/{y}/{x}',
        proj: 'wgs84',
        zooms: [2, 28],
        zIndex: 4
    })

})
</script>
<style lang="less" scoped>
.app-container {
    width: 100%;
    height: 100%;
}
</style>`这是我的测试代码，瓦片是内网的无法访问，加载的是一块区域底图不是全地图的。可以看看我的图片

**Comment by yangyanggu** [comment]
单纯的从代码上来看没什么问题，你可以先从控制台的network看下加载的图片是否正常

**Comment by yangyanggu** [comment]
也可以开启插件的debug参数，看瓦片上能否出现红色的瓦片编号

**Comment by yangyanggu** [comment]
组件库里的用的插件跟你使用的本质上是一样的，这个没有瓦片目前也不好定位原因在哪

**Comment by dufeng-code** [comment]
方便加个wx吗，我有html版本让你调试

**Comment by yangyanggu** [comment]
407042815  你加这个QQ吧
