### ISSUE TITLE
引入使用报错

### ISSUE THREAD

**Issue by github1359930721** [yangyanggu/amap-xyz-layer#3]
![image](https://github.com/user-attachments/assets/e344cd9a-a75d-41fa-a4ac-fa0f3940b3e6)

**Comment by yangyanggu** [comment]
单纯这个错误看不出东西，你贴一下你的代码吧

**Comment by github1359930721** [comment]
> 单纯这个错误看不出东西，你贴一下你的代码吧
![image](https://github.com/user-attachments/assets/819e0db5-92c5-464a-a9f3-f4286e4052a7)

**Comment by github1359930721** [comment]
对高德地图的版本是不是有要求限制

**Comment by yangyanggu** [comment]
不要把gaodeLayer那个变量放到layers里，你这map.add(layers)肯定会有问题，我的这个插件毕竟不是高德自己的插件，不能走这个通道，你就正常的new CustomXyzLayer就可以添加进地图了

**Comment by github1359930721** [comment]
> 不要把gaodeLayer那个变量放到layers里，你这map.add(layers)肯定会有问题，我的这个插件毕竟不是高德自己的插件，不能走这个通道，你就正常的new CustomXyzLayer就可以添加进地图了

对高德地图 版本是不是有最低要求

**Comment by yangyanggu** [comment]
2.0的版本就行了
